spring.application.name=AlertSphere

spring.mongodb.uri=mongodb+srv://ishaank704_db_user:h7gAYcfNoKTuyXsk@alertsphere.dibjw5b.mongodb.net/AlertSphere?retryWrites=true&w=majority&appName=AlertSphere
spring.mongodb.auto-index-creation=true


spring.data.redis.host=redis-15173.c264.ap-south-1-1.ec2.cloud.redislabs.com
spring.data.redis.port=15173
spring.data.redis.password=r3e0DO24If3fKlfZNU4dNTL06kHopWIS

spring.kafka.bootstrap-servers=127.0.0.1:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.group-id=alert-sphere-mail
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.properties.max.block.ms=2000
spring.kafka.producer.properties.request.timeout.ms=3000
spring.kafka.producer.properties.delivery.timeout.ms=5000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ishaan.khan_cs22@gla.ac.in
spring.mail.password=rjwa aujv vpje lfmq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

weather.api.url=https://api.openweathermap.org/data/2.5/weather
weather.api.key=ee80b049bff96d9e49a56c5c015261eb
weather.cache.ttl-minutes=5

alerts.weather-check.delay-ms=300000
alerts.weather-check.enabled=true
alerts.kafka.email-topic=weather-alert-email
alerts.kafka.consumer.enabled=true
alerts.kafka.devassist-incident-topic=incident-events
alerts.kafka.devassist-notification-topic=notification-events
alerts.kafka.devassist-consumer-group=alert-sphere-devassist
alerts.devassist.consumer.enabled=true
