spring.application.name=AlertSphere
spring.mongodb.uri=mongodb+srv://ishaank704_db_user:gq4U097jApbxvvRX@cluster0.nxoj2d9.mongodb.net/AlertSphere?retryWrites=true&w=majority&appName=Cluster0
spring.mongodb.auto-index-creation=true
